name: ci

on: workflow_dispatch

jobs:
  greet:
    name: Greet
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
        version: [10, 12]
    runs-on: ${{ matrix.os }}
    steps:
      - name: greetings
        run: echo "Hello world!"
